### PR TITLE
added --output-on-failure to ctest run

### LINKED ISSUE #51: Add --output-on-failure to ctest run
@kgerheiser is it safe to say we always want --output-on-failure on every CI run?

We also have verbose, is there any other option we should be using? If we can come up with a canonical solution we can apply it everywhere.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #51 

added --output-on-failure to ctest run

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@BrianCurtis-NOAA I think turning on this option will help with your testing tasks...

**Comment by BrianCurtis-NOAA** [comment]
Nevermind. That's an old variable.

**Comment by edwardhartnett** [comment]
Perhaps --verbose already does what --output-on-failure needs to do? In which case, perhaps we just want --output-on-failure...

**Comment by kgerheiser** [comment]
Yes, you might just want `--output-on-failure`. `--verbose` is the same thing, except all the time.

**Review by kgerheiser — APPROVED** [review]

**Pull request merged**
