### PR TITLE
Upload code coverage using gcovr

### LINKED ISSUE #48: add code coverage to CI testing
@kgerheiser can you add the code coverage magic to this repo?

### PR DESCRIPTION
**Pull request by kgerheiser**
Fix #48

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]
Nice work! Thanks!

**Comment by kgerheiser** [comment]
Something is not right with the html output

**Comment by kgerheiser** [comment]
I think it's related to all of the `include` statements. gcovr seems like it's not picking up the correct source files. It's just getting the `tst_ncio.f90` file.

**Comment by edwardhartnett** [comment]
Should this PR be taken down? Or is it still active?

**Comment by kgerheiser** [comment]
I might be able to find a workaround, but as is the code coverage doesn't work well.

**Comment by edwardhartnett** [comment]
What's the problem with code coverage here? It seems that the macos build is stuck - is this related to code coverage? Or some other problem?

**Comment by kgerheiser** [comment]
Take a look at the artifact produced here: https://github.com/kgerheiser/NCEPLIBS-ncio/actions/runs/994758656

The actual code coverage report generated is wrong. It doesn't pick up the source files because they're all included with `include()`.

**Comment by edwardhartnett** [comment]
Well ain't that a kick in the teeth? The same thing is really messing with the doxygen build as well. (Though I have recently have found an answer there - I've got to try it out...)

One trick I've used in the past is to generate a pre-processed .f90 version of the file, and pass that to the test code coverage. However, isn't the test code coverage tool smart enough to pre-process the fortran code? 

Well shoot! I see our files are .f90 - shouldn't they all be .F90? That usually indicates to the tools that the preprocessor needs to be run on the code.

**Comment by kgerheiser** [comment]
The code here uses `include()` which is part of the Fortran language, not the pre-processor with `#include`.

**Comment by kgerheiser** [comment]
Closing for now

**Pull request closed without merging**
